name: masOS

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    env: 
      VK_VERSION: "1.2.135.0"
      INSTALL_LOCATION: "$GITHUB_WORKSPACE/../vulkan_sdk/"

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Vulkan
        id: cache-vulkan-sdk
        uses: actions/cache@v1
        with:
          path: ${{ env.VULKAN_SDK }}
          key: vulkan-sdk-${{ env.VK_VERSION }}

      - name: Setup Vulkan 
        if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
        run: |
          curl -LS -o ../vulkansdk.tar.gz \
            https://sdk.lunarg.com/sdk/download/1.2.135.0/mac/vulkansdk-macos-1.2.135.0.tar.gz
          mkdir -p "${{ env.INSTALL_LOCATION }}"
          echo "CREATED"
          tar xfz ../vulkansdk.tar.gz -C "${{ env.INSTALL_LOCATION }}"
          echo "EXTRACTED"
          export VK_VERSION=1.2.135.0
          export VULKAN_SDK=${{ env.INSTALL_LOCATION }}/vulkansdk-macos-1.2.135.0/macOS
          echo "EXPORTED"
          ls ${{ env.INSTALL_LOCATION }}
          ls ${{ env.INSTALL_LOCATION }}/vulkansdk-macos-1.2.135.0
          ls ${{ env.INSTALL_LOCATION }}/vulkansdk-macos-1.2.135.0/macOS
          ls $VULKAN_SDK/lib
          
      - name: setup dependencies
        run: | 
          export VULKAN_SDK=${{ env.INSTALL_LOCATION }}/vulkansdk-macos-1.2.135.0/macOS
          make setup
