name: masOS

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    env: 
      VK_VERSION: "1.2.135"
      INSTALL_LOCATION: "$GITHUB_WORKSPACE/../vulkan_sdk"
      VULKAN_SDK: "${{env.INSTALL_LOCATION}}/vulkansdk-macos-1.2.135.0/macOS"

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Vulkan
        id: cache-vulkan-sdk
        uses: actions/cache@v1
        with:
          path: ${{ env.INSTALL_LOCATION }}
          key: vulkan-sdk-${{ env.VK_VERSION }}

      - name: Setup Vulkan 
        if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
        run: |
          curl -LS -o ../vulkansdk.tar.gz \
            https://sdk.lunarg.com/sdk/download/1.2.135.0/mac/vulkansdk-macos-1.2.135.0.tar.gz
          mkdir -p "${{ env.INSTALL_LOCATION }}"
          tar xfz ../vulkansdk.tar.gz -C "${{ env.INSTALL_LOCATION }}"
          
      - name: setup dependencies
        run: make setup

      - name: build project
        run: make bin/app
        
      - name: clean
        run: make clean
        
      - name: make bin/app CXX=g++
        run: make bin/app CXX=g++
