name: masOS

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    env: 
      VK_VERSION: "1.2.135.0"
      VULKAN_SDK: "$GITHUB_WORKSPACE/../vulkan_sdk/"

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Vulkan
        id: cache-vulkan-sdk
        uses: actions/cache@v1
        with:
          path: ~/VulkanSDK/${{ env.VK_VERSION }}
          key: vulkan-sdk-${{ env.VK_VERSION }}

      - name: Setup Vulkan 
        if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
        run: |
          curl -LS -o ../vulkansdk.tar.gz \
            https://sdk.lunarg.com/sdk/download/1.2.135.0/mac/vulkansdk-macos-1.2.135.0.tar.gz
          tar xfz vulkansdk.tar.gz -C "${{ env.VULKAN_SDK }}"
          cd ${{ env.VULKAN_SDK }}
          ls
