name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env: 
      VK_VERSION: "1.2.176.1"
      INSTALL_LOCATION: "$GITHUB_WORKSPACE/../vulkan_sdk"

    steps:

      - uses: actions/checkout@v2
      
      - name: Cache Vulkan
        id: cache-vulkan-sdk
        uses: actions/cache@v1
        with:
          path: ${{ env.INSTALL_LOCATION }}
          key: vulkan-sdk-${{ env.VK_VERSION }}
      
      - name: Setup Vulkan 
        if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
        run: |
          curl -LS -o ../vulkansdk.tar.gz \
            https://sdk.lunarg.com/sdk/download/${{ env.VK_VERSION }}/linux/vulkansdk-linux-x86_64-${{ env.VK_VERSION }}.tar.gz
          mkdir -p "${{ env.INSTALL_LOCATION }}"
          tar xfz ../vulkansdk.tar.gz -C "${{ env.INSTALL_LOCATION }}"
          ls ${{ env.INSTALL_LOCATION }}/${{ env.VK_VERSION }}/vulkansdk
          ls ${{ env.INSTALL_LOCATION }}/${{ env.VK_VERSION }}/x86_64
