name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env: 
      VK_VERSION: "1.2.176.1"
      INSTALL_LOCATION: "C:"
      VULKAN_SDK: "C:\\VulkanSDK\\1.2.176.1"

    steps:
      - uses: actions/checkout@v2
      - name: Cache Vulkan SDK
        id: cache-vulkan-sdk
        uses: actions/cache@v1
        with:
         path: "C:\\VulkanSDK\\"
         key: vulkan-sdk-${{ env.VK_VERSION }}
      - name: Setup Vulkan
        if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
        run: |
           Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ env.VK_VERSION }}/windows/VulkanSDK-${{ env.VK_VERSION }}-Installer.exe" -OutFile VulkanSDK.exe
           $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
           $installer.WaitForExit();
     
      - name: Setup dependencies
        run: mingw32-make setup
        
      - name: make bin/app
        run: mingw32-make bin/app
      
      - name: 'export binary'
        uses: actions/upload-artifact@v2
        with:
            name: app.exe
            path: bin/app.exe
